before_script:
  - export GRADLE_USER_HOME=`pwd`/.gradle

# This file is a template, and might need editing before it works on your project.
# This is the Gradle build system for JVM applications
# https://gradle.org/
# https://github.com/gradle/gradle
# search for official images here: https://hub.docker.com/_/gradle/?tab=tags&page=1&ordering=last_updated
# image: gradle:alpine
image: gradle:7.3.3-jdk17-alpine


stages:
  - build
  - test

build:
  stage: build
  script: ./gradlew --build-cache assemble
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: push
    paths:
      - build
      - .gradle

test:
  stage: test
  script: ./gradlew test
  cache:
    key: "$CI_COMMIT_REF_NAME"
    policy: pull
    paths:
      - build
      - .gradle
  artifacts:
    reports:
      junit:
        - app/build/test-results/TEST-*.xml
        - app/build/test-results/test/TEST-*.xml
