/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package assignment1;

/**
 * This is the generated Hello World Greeting App.
 */
public class App {

  /**
   * Returns a nice greeting message.
   *
   * @return the greeing message.
   */
  public String getGreeting() {
    return "Hello World!!";
  }

  /**
   * The App starting point.
   *
   * @param args Unused program arguments.
   */
  public static void main(String[] args) {
    App theApp = new App();
    System.out.println(theApp.getGreeting());
  }
}
